version: '3.1'
services:
  mongo:
    image: mongo
    container_name: "eua_mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './dockervolume/mongodb:/data/db'
      ## if you need to restore from dump use volume
      # - './dockervolume/mongodump:/data/dump'
    ports:
      - 27017:27017
